### ISSUE TITLE
Configuration to allow overwriting files

### ISSUE THREAD

**Issue by ThePuzzlemaker** [fluxxcode/egui-file-dialog#101]
As the title says. I believe this should be a configurable option, instead of a fixed error.

**Comment by fluxxcode** [comment]
Thanks for the issue. Do you mean that when saving a file you can overwrite an existing one?

**Comment by ThePuzzlemaker** [comment]
Yes, currently it says something along the lines of "file already exists" when trying to select a file that already exists to overwrite.

**Comment by crumblingstatue** [comment]
Ideally it should ask in a modal dialog "The file already exists. Do you want to overwrite?"

**Comment by fluxxcode** [comment]
I have now implemented the modal. Do you have any suggestions for improvement?

https://github.com/fluxxcode/egui-file-dialog/assets/55352293/a1f4aa30-3e4c-44b8-8378-3f8c57002498

**Comment by crumblingstatue** [comment]
That looks good, thank you! I'm gonna give it a test in my application.

One suggestion that comes to mind. Maybe "Abort" sounds a little dramatic. "Cancel" might be a better word to use.

**Comment by fluxxcode** [comment]
Changed and merged into develop 👍🏻
