### ISSUE TITLE
Hexerator wishlist

### ISSUE THREAD

**Issue by crumblingstatue** [fluxxcode/egui-file-dialog#116]
My egui project, [Hexerator](https://github.com/crumblingstatue/hexerator) has switched from rfd to egui-file-dialog, but right now it's using a fork with custom patches to accommodate Hexerator's needs.
The eventual goal is to not have a fork, and just depend on upstream egui-file-dialog directly.
This is a wishlist of features that currently a fork is required for.

- [x] 1.) Ability to modify pinned folders directly.
  I have some Hexerator specific pinned folders that I want Hexerator to manage, instead of relying on user-wide pinned folders.
  It shouldn't even require "persistence" to work, since I want to store the folders myself, without relying on egui-file-dialog to do it for me.
  Downstream patch: ~~Make `FileDialogConfig` and `DirectoryEntry` public. This way, the pinned folders can be read and written to by the application.~~
- [x] 2.) Home shortcut key
  I'm (and likely many other) unix users expect the `~` key to work to access the home directory quickly.
  Maybe this should have a different default on windows, although I don't see an obvious choice for what it should be on windows, so maybe it's fine for it to be `~` there as well.
  Downstream patch: [Add home_edit_path key binding](https://github.com/fluxxcode/egui-file-dialog/commit/33ddc1ef33e51c3166f3935e0220ca1a80752dca)

**Comment by fluxxcode** [comment]
1: Are the quick access sections not suitable for this? \
You can add your own sections via the backend:
```rust
file_dialog = FileDialog::default()
    .add_quick_access("Hexerator", |s| {
        s.add_path("Some path 1", "./path-1");
        s.add_path("Some path 2", "./path-2");
    })
```
And you can access the config with `file_dialog.config_mut()`.

**Comment by crumblingstatue** [comment]
> And you can access the config with `file_dialog.config_mut()`.

Ah, good catch. I think I used to need that because the storage and config were two different structs, and I was getting overlapping borrows by borrowing the config through `config_mut(&mut self)`, and also trying to access the storage.

But now the storage is in the config, so it's fine that `config_mut()` borrows self.

I'll cross that one off the list.

**Comment by fluxxcode** [comment]
The shortcut key is now implemented.

Let me know if you have any other ideas!

**Comment by jannistpl** [comment]
@crumblingstatue I just happened to see that you were having problems when storage and config were separate. With the PR https://github.com/jannistpl/egui-file-dialog/pull/259 I restored that condition. Was that not a good idea? Will it cause more problems for you and other users?

**Comment by crumblingstatue** [comment]
I'm gonna have to try out the new version with Hexerator to see if I can upgrade without losing any functionality. 

I'll try doing that today and report back here.

**Comment by crumblingstatue** [comment]
Yeah, I'm having trouble porting this code

```Rust
fn transfer_pinned_folders_to_file_dialog(gui: &mut Gui, cfg: &mut Config) {
    let dia_cfg = gui.fileops.dialog.config_mut();
    // Remove them from the config, as later it will be filled with
    // the pinned dirs from the dialog
    for dir in cfg.pinned_dirs.drain(..) {
        dia_cfg.storage.pinned_folders.push(DirectoryEntry::from_path(
            dia_cfg,
            &dir,
            &NativeFileSystem,
        ));
    }
}
```

- `PinnedFolder` is not public, so I can't construct it to push to pinned folders.
- I can't borrow `config_mut()` and `storage_mut()` at the same time, since they both borrow `self`.

I'm not sure if there is a supported way of adding custom pinned folders programmatically, which is what I'm trying to do.

**Comment by jannistpl** [comment]
Oh `PinnedFolders` is not public? I have to fix it tomorrow.

The bigger problem will be the one with borrowing. At the moment there are only the quick access paths that you can add. Editing pinned folder is not intended. But why do you need to borrow the `FileDialogConfig` mutable for this? Isn't it enough if the storage is mutable borrowed?

**Comment by crumblingstatue** [comment]
Ah, it seems it was needed because DirectoryEntry::from_path needed the config, but maybe with the new API the config isn't needed anymore.

**Comment by jannistpl** [comment]
Fixed the `PinnedFolder` structure being private. Let me know if you can migrate your code now.

**Comment by crumblingstatue** [comment]
Thank you, I managed to migrate to the new API!
