### ISSUE TITLE
Attempt to save path entered into top bar if it's not a (existing) directory

### ISSUE THREAD

**Issue by crumblingstatue** [fluxxcode/egui-file-dialog#159]
Extend the #150 behavior to saving paths.

With the same reasoning that the user might already have a path in mind, like they want to save to `/tmp/foo.txt`.
![image](https://github.com/user-attachments/assets/ec8b74d9-1f76-462d-8257-be07cb8fab6e)

**Comment by fluxxcode** [comment]
I have implemented it on the referencing PR. Could you take a quick look to see if this is the behavior you expect?

**Comment by crumblingstatue** [comment]
I left a comment regarding files without extensions, but otherwise it seems to be working, thank you for implementing!
