### ISSUE TITLE
Place label not translated/customized

### ISSUE THREAD

**Issue by thmxv** [fluxxcode/egui-file-dialog#179]
Hi, Thanks for this crate.

I could make a PR, but I supposed, (as it is a small error) it would be easier/quicker to just post it here. Correct me if I am wrong and I will do a fork/commit/PR.

The issue is on line `1690` of `src/file_dialog.rs` where:
```rust
ui.label(self.config.labels.heading_places.as_str());
```
need to be changed to:
```rust
ui.label(&labels.heading_places);
```

**Comment by fluxxcode** [comment]
Hey, thank you for the issue! What version of the crate are you using?

**Comment by fluxxcode** [comment]
Ye you are right, I'm able to reproduce it on develop. Will fix it. Thank you :)

**Comment by thmxv** [comment]
> Hey, thank you for the issue! What version of the crate are you using?

I am using `0.6.1`, which also has the bug. But the fix is for after the last commit of the git `develop` branch.

Thanks.
