### ISSUE TITLE
Drag&Drop should select dropped item

### ISSUE THREAD

**Issue by hacknus** [fluxxcode/egui-file-dialog#196]
Sorry, I noticed this a bit too late. I think we should select the item that we dropped. Right now it only opens up the folder or the parent folder (if we dropped a file). We somehow need to call 
`self.select_item()` but I'm not sure how we can access it?

```rust
if let Some(dropped_file) = i.raw.dropped_files.last() {
    if let Some(path) = &dropped_file.path {
        if path.is_dir() {
            // if we dropped a directory, go there
           self.load_directory(path.as_path());
            new_file_dropped = true;
        } else if let Some(parent) = path.parent() {
            // else, go to the parent directory
            self.load_directory(parent);
            let mut entry = DirectoryEntry::from_path(&self.config, &path);
            self.select_item(&mut entry);
            new_file_dropped = true;
        }
    }
}
```

This here somehow only works if we drop the file a second time, after the first time it seems that it is only briefly selected and then cleared again. Do you have any idea, how we get the item here?
We should also select the directory, if we are in the corresponding mode.

**Comment by fluxxcode** [comment]
That's how it should work. I'll have to take a closer look tomorrow to see what's going wrong.

**Comment by hacknus** [comment]
The issue is here in `update_directory_content()`:

```rust
DirectoryContentState::Finished => {
         if let Some(dir) = self.current_directory() {
             let mut dir_entry = DirectoryEntry::from_path(&self.config, dir);
            self.select_item(&mut dir_entry);
        }
    false
}
```

after the directory is loaded, it selects the directory and overrides the dropped file. I think we need to have an if-statement there or something... Do you have an idea?
