### ISSUE TITLE
Macintosh HD shown twice (macOS)

### ISSUE THREAD

**Issue by hacknus** [fluxxcode/egui-file-dialog#201]
On macOS, the egui-file-dialog works well, but `Macintosh HD` is shown twice.
- as `/` (read-only) gets pulled by `fs::read_dir("/Volumes")` as. `/Volumes/Macintosh HD` which I think is a symlink
- as `/System/Volumes/Data` (user-data) gets pulled by `Disk::from_sysinfo_disk(disk, canonicalize_paths)`

This seems to be caused by the APFS file system and Apple's system integrity protection. 

All the quick-action folders in the side bar point to `/`, everything is mapped there when using the command line etc on a Mac, so we should probably also use this.

I'll look into this and also verify that using `/` will not result in any write permission issues.

**Comment by fluxxcode** [comment]
Fixed
