### ISSUE TITLE
Bundles appear with folder icon (macOS)

### ISSUE THREAD

**Issue by hacknus** [fluxxcode/egui-file-dialog#209]
On macOS, applications are bundles in directories with names `bundlexyz.app`

In macOS, they are displayed with an icon that is usually located in `bundlexyz.app/Contents/Resources/AppIcon.icns` or `bundlexyz.app/Contents/Resources/bundlexyz.icns` 

In the egui-file-dialog, all bundles are displayed with the directory icon. How is this handled on other operating systems?
Should we leave it like this?

It might be too much overhead to load in the icons of the bundles to display them. The egui-file-dialog will probably primarily be used for interacting with files and directories, not with applications.

EDIT: frameworks (`.framework`) and plugins (`.bundle`) are essentially also directories. They are usually displayed with a LEGO-block-ish icon. Here, the potential of interfacing with such items might be higher than with application bundles. Would also be very easy to display them with a different logo, since it is not unique for each item.

**Comment by fluxxcode** [comment]
Hey, currently only unicode icons are supported. However, you can customize the unicode icon of specific files and folders with `FileDialog::set_file_icon` (or something similar).There is also an example of this in the documentation and readme.

I had also thought about supporting images that are loaded from the disk in addition to Unicode icons. But this is only planned at the moment and needs some refactoring.

**Comment by hacknus** [comment]
Then I think we will keep the potential `.app` icon change for the future.
I'll look into a unicode icon for `.bundle` `.framework` in the meantime.

**Comment by hacknus** [comment]
I noticed in the docs that `.show_hidden_option(true)` is not included for the icon demo, although the example is the `.gitignore` file. And I think we should also recommend to include all lower and upper case extensions. Like this:

```rust
            .show_hidden_option(true)
            .set_file_icon(
                "🖹",
                Arc::new(|path| path.extension().unwrap_or_default().to_ascii_lowercase() == "md"),
```

I think we can close this issue then for now.

**Comment by fluxxcode** [comment]
Which example do you mean exactly? In the readme under customization no `show_hidden_option` is set, so it is activated by default.

I would also keep the examples as small as possible. File extensions are usually case sensitive. Don't know if it's different on Mac 🤔

**Comment by hacknus** [comment]
Ah sorry, yes, I didn't notice that it is set by default.

Yeah on mac they are not case sensitive. I've encountered markdown often as `md` and also `MD`.
